# Generated by Django 5.1.7 on 2025-03-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
